# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"length": "ch01_problem01.ipynb",
         "DataManager": "ch01_problem01.ipynb",
         "attach_std": "ch01_problem01.ipynb",
         "plot_scatter": "ch01_problem01.ipynb",
         "plot_predictions_actual": "ch01_problem01.ipynb",
         "plot_predictions_residuals": "ch01_problem01.ipynb",
         "plot_predictions": "ch01_problem01.ipynb",
         "wires_facet_theme": "ch01_problem01.ipynb",
         "piston": "ch01_problem02.ipynb",
         "scale_to_range": "ch01_problem02.ipynb",
         "scale_columns": "ch01_problem02.ipynb",
         "plot_heatmap_facets": "ch01_problem02.ipynb",
         "longify_grid": "ch01_problem02.ipynb",
         "make_fit_dataframe": "ch01_problem02.ipynb",
         "Modeler": "ch01_problem02.ipynb",
         "LinearModeler": "ch01_problem02.ipynb",
         "RFModeler": "ch01_problem02.ipynb",
         "GPModeler": "ch01_problem02.ipynb",
         "PistonModeler": "ch01_problem02.ipynb"}

modules = ["ch01_problem01.py",
           "ch01_problem02.py"]

doc_url = "https://fastai.github.io/surrogates/"

git_url = "https://github.com/fastai/surrogates/tree/master/"

def custom_doc_links(name): return None
