# AUTOGENERATED! DO NOT EDIT! File to edit: ch01_problem02.ipynb (unless otherwise specified).

__all__ = ['piston', 'scale_to_range']

# Cell
def piston(M, S, V0, k, P0, Ta, T0):
    A = P0*S + 19.62*M - k*V0 / S
    V = (S / (2*k)) * (np.sqrt(A**2 + 4*k * (P0*V0 / T0) * Ta) - A)
    sq_denom = k + S**2 * (P0*V0 / T0) * (Ta / V**2)
    return 2 * np.pi * np.sqrt(M / sq_denom)


def scale_to_range(v: pd.Series, target_min: float, target_max: float) -> pd.Series:
    vmin, vmax = v.min(), v.max()
    return ((v - vmin) / (vmax - vmin)) * (target_max - target_min) + target_min